channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==12.8.2 # https://rpaframework.org/releasenotes.html
      - pandas==1.3.4
      - beautifulsoup4==4.10.0
      - bs4==0.0.1